# Generated by Django 2.0.2 on 2018-06-05 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grape',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Wine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winetype', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('region', models.CharField(max_length=150)),
                ('winery', models.CharField(max_length=150)),
                ('vintage', models.PositiveSmallIntegerField()),
                ('serving_temp', models.CharField(max_length=50)),
                ('contents', models.DecimalField(decimal_places=2, max_digits=4)),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
                ('aroma', models.CharField(max_length=150)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('url', models.URLField()),
                ('vendor_code', models.CharField(max_length=50, unique=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('grapes', models.ManyToManyField(to='wines.Grape')),
            ],
        ),
    ]
