# Generated by Django 2.0.2 on 2018-06-07 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wines', '0002_auto_20180607_0958'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grape',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='vendor',
            options={'ordering': ['name']},
        ),
        migrations.RenameField(
            model_name='vendorwine',
            old_name='quantity',
            new_name='bottles',
        ),
        migrations.RemoveField(
            model_name='wine',
            name='contents',
        ),
        migrations.AddField(
            model_name='wine',
            name='quantity',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
