# Generated by Django 2.0.2 on 2018-06-07 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wines', '0003_auto_20180607_1148'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wine',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='vendorwine',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendors', to='wines.Vendor'),
        ),
        migrations.AlterField(
            model_name='vendorwine',
            name='wine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wines', to='wines.Wine'),
        ),
    ]
