# Generated by Django 2.0.2 on 2018-06-07 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wines', '0004_auto_20180607_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wine',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='wines', to='wines.Country'),
        ),
    ]
