# Generated by Django 2.0.2 on 2018-06-07 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wines', '0005_auto_20180607_1354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wine',
            name='quantity',
        ),
        migrations.AddField(
            model_name='vendorwine',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0.75, max_digits=4),
        ),
        migrations.AlterField(
            model_name='vendorwine',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
    ]
