# Generated by Django 2.0.2 on 2018-06-07 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wines', '0006_auto_20180607_1420'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendorwine',
            name='bottles',
        ),
        migrations.AddField(
            model_name='vendorwine',
            name='volume',
            field=models.DecimalField(decimal_places=3, default=0.75, max_digits=5),
        ),
        migrations.AlterField(
            model_name='vendorwine',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
