# Generated by Django 2.0.2 on 2018-06-08 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wines', '0007_auto_20180607_1543'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wine',
            name='serving_temp',
        ),
        migrations.RemoveField(
            model_name='wine',
            name='vintage',
        ),
    ]
