# Generated by Django 2.0.2 on 2018-06-08 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wines', '0008_auto_20180608_1153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wine',
            name='aroma',
        ),
        migrations.RemoveField(
            model_name='wine',
            name='grapes',
        ),
        migrations.DeleteModel(
            name='Grape',
        ),
    ]
