# Generated by Django 2.0.2 on 2018-06-08 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wines', '0009_auto_20180608_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
