# Generated by Django 2.0.2 on 2018-06-08 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wines', '0010_auto_20180608_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='wine',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
