# Generated by Django 2.0.2 on 2018-06-11 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wines', '0012_vendor_plugin'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
