# Generated by Django 2.0.2 on 2018-06-11 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wines', '0013_vendor_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='max_pages',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='vendor',
            name='page',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendor',
            name='product',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
    ]
