# Generated by Django 2.0.2 on 2018-06-13 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wines', '0015_rater_winerating'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='stopwords',
            field=models.CharField(default='', max_length=250),
        ),
    ]
