# Generated by Django 2.0.2 on 2018-06-14 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wines', '0017_auto_20180613_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='winerating',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='winerating',
            name='url',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
