# Generated by Django 2.0.2 on 2018-06-14 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wines', '0018_auto_20180614_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='rater',
            name='limit',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
