# Generated by Django 2.0.2 on 2018-06-15 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wines', '0021_rater_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorwine',
            name='wine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendors', to='wines.Wine'),
        ),
    ]
