# Generated by Django 2.0.2 on 2018-06-24 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wines', '0023_auto_20180618_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='winerating',
            name='keywords',
            field=models.CharField(default='', max_length=250),
        ),
    ]
