# Generated by Django 2.0.2 on 2018-06-25 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wines', '0024_winerating_keywords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='winerating',
            name='url',
            field=models.URLField(default=''),
        ),
    ]
