# Generated by Django 2.0.2 on 2018-06-25 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wines', '0025_auto_20180625_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='winerating',
            name='keywords',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='winerating',
            name='url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
