# Generated by Django 2.0.2 on 2018-06-26 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wines', '0026_auto_20180625_1113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='winerating',
            name='keywords',
        ),
        migrations.AddField(
            model_name='vendorwine',
            name='title',
            field=models.CharField(default='', max_length=150, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wine',
            name='keywords',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
    ]
