# Generated by Django 2.0.2 on 2018-06-26 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wines', '0027_auto_20180626_0835'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wine',
            name='keywords',
        ),
    ]
