# Generated by Django 2.0.2 on 2018-06-26 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wines', '0029_wine_keywords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorwine',
            name='wine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendors', to='wines.Wine'),
        ),
    ]
