# Generated by Django 2.0.2 on 2018-06-26 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wines', '0030_auto_20180626_0844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorwine',
            name='title',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='vendorwine',
            name='url',
            field=models.URLField(unique=True),
        ),
    ]
