# Generated by Django 2.0.2 on 2018-06-26 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wines', '0032_auto_20180626_0941'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vendorwine',
            unique_together=set(),
        ),
    ]
