# Generated by Django 2.0.2 on 2018-06-26 10:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wines', '0033_auto_20180626_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorwine',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
