# Generated by Django 2.0.2 on 2018-06-29 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wines', '0034_auto_20180626_1258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wine',
            name='keywords',
        ),
        migrations.AddField(
            model_name='vendorwine',
            name='keywords',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
    ]
