# Generated by Django 2.0.2 on 2018-06-29 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wines', '0035_auto_20180629_0955'),
    ]

    operations = [
        migrations.AddField(
            model_name='wine',
            name='url',
            field=models.URLField(default='', unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='wine',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
