# Generated by Django 2.0.2 on 2018-07-02 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wines', '0036_auto_20180629_1031'),
    ]

    operations = [
        migrations.CreateModel(
            name='WineStyle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.RemoveField(
            model_name='wine',
            name='winetype',
        ),
        migrations.AddField(
            model_name='wine',
            name='style',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='wines', to='wines.WineStyle'),
        ),
    ]
