# Generated by Django 2.0.2 on 2018-07-02 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wines', '0037_auto_20180702_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='winestyle',
            name='name',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
