# Generated by Django 2.0.2 on 2018-07-10 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wines', '0038_auto_20180702_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='winestyle',
            name='acidity',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='winestyle',
            name='body',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='winestyle',
            name='url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
