# Generated by Django 2.0.2 on 2018-07-10 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wines', '0040_auto_20180710_1415'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wine',
            name='color',
        ),
        migrations.AddField(
            model_name='winestyle',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
